name: Build and Push latest versions

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest PostgreSQL version
      id: pg_latest
      run: |
        export latest_version="$(curl -sS https://www.postgresql.org/ftp/source/ | grep -oP '(?<=v)[0-9]+\.[0-9]+' | sort -V | tail -1)"
        echo "version=${latest_version}" >> "$GITHUB_OUTPUT"
        echo "major_version=$(echo ${latest_version} | cut -d '.' -f 1)" >> "$GITHUB_OUTPUT"

    - name: Get latest RDKit version
      id: rdkit_latest
      run: |
        echo version="$(curl -sS "https://api.github.com/repos/rdkit/rdkit/releases/latest" | jq -r '.tag_name' | sed 's/Release_//')" >> "$GITHUB_OUTPUT"

    - name: Check if image already exists
      id: check_image
      run: |
        export EXISTS=0
        if ! docker manifest inspect ghcr.io/${{ github.repository }}/postgres-rdkit:postgres-${{ steps.pg_latest.outputs.version }}-rdkit-${{ steps.rdkit_latest.outputs.version }} > /dev/null 2>&1; then
          EXISTS=1
        fi
        echo "exists=$EXISTS" >> "$GITHUB_OUTPUT"

    - name: Build and push
      if: steps.check_image.outputs.exists == '1'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/postgres-rdkit:postgres-${{ steps.pg_latest.outputs.version }}-rdkit-${{ steps.rdkit_latest.outputs.version }}
        build-args: |
          postgres_image_version=${{ steps.pg_latest.outputs.version }}
          postgres_major_version=${{ steps.pg_latest.outputs.major_version }}
          rdkit_git_ref=Release_${{ steps.rdkit_latest.outputs.version }}
