name: Sync workflow files and README

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can push to other branches

    - name: Set up Git
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

    - name: Fetch all branches
      run: |
        git fetch --all

    - name: Merge changes into other branches
      run: |
        for branch in $(git branch -r --list 'origin/postgres-*rdkit-*'); do
          branch_name=$(echo $branch | sed 's/^origin\///')  # Remove 'origin/' prefix
          git checkout $branch_name
          git merge origin/main --allow-unrelated-histories -m "Merged main into $branch_name"
          git push origin $branch_name
        done
        git checkout main
